### ISSUE TITLE
From option

### ISSUE THREAD

**Issue by SergeyMiracle** [acrazing/webpack-ssh-deploy-plugin#1]
Is there way to set from where take assets? And also ignore files/directories?

**Comment by acrazing** [comment]
@SergeyMiracle Currently could not ignore, but you can use `cache` option to let a asset just deploy once rather than deploy every time when use `--watch` option.

**Comment by SergeyMiracle** [comment]
@acrazing ok i see, and what about source path? (from: 'local/folder')

**Comment by acrazing** [comment]
The path rewrite is not supported, you can just use the `root` option to set the root directory to place assets on remote server, just like the option `output.path` in webpack.
